[package]
name = "pcrl"
version = "0.1.0"
edition = "2021"

[dependencies]
itoa = { version = "1.0.6", optional = true }
unicode-segmentation = { version = "1.10.1", optional = true }

[features]
default = []
format = ["dep:itoa", "dep:unicode-segmentation"]
