[package]
name = "python"
version = "0.1.0"
edition = "2021"

[lib]
name = "pcrllib"
crate-type = ["cdylib"]

[dependencies]
pcrl = { path = "../core" }
pyo3 = { version = "0.19.0", features = ["abi3-py311"] }
